import Link from "next/link";
import { AccessRelationshipForm, ResourceForm } from "@/components/security-forms";
import { requireSecurityContext } from "@/lib/security/context";
import { hasPermission } from "@/lib/security/permissions";
import { listAccessRelationships, listMachineIdentities, listResources } from "@/lib/security/repositories";

export default async function AccessGraphPage() {
  const context = await requireSecurityContext("view_security_data"); const [identities, resources, relationships] = await Promise.all([listMachineIdentities(context), listResources(context), listAccessRelationships(context)]); const identityOptions = identities.map((identity) => ({ id: identity.id, name: identity.name })); const resourceOptions = resources.map((resource) => ({ id: resource.id, name: resource.name })); const canManage = hasPermission(context.role, "manage_security_inventory"); const privileged = relationships.filter((relationship) => relationship.privileged).length; const observed = relationships.filter((relationship) => relationship.provenance === "observed" || relationship.source === "csv_import" || relationship.source === "connector").length; const connectedIdentities = new Set(relationships.map((relationship) => relationship.machine_identity_id)).size;
  return <section><div className="flex flex-col gap-5 border-b border-[var(--line)] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--teal)]">Discover · Access intelligence</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-[var(--navy)] sm:text-4xl">Access relationships</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">See which named app or system account can reach which resource, with privilege and evidence context—not database IDs.</p></div>{canManage && <Link className="button-primary focus-ring text-center" href="/import">Discover from CSV</Link>}</div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="panel p-4"><p className="text-xs font-semibold text-[var(--muted)]">Known access paths</p><p className="mt-2 text-2xl font-semibold text-[var(--navy)]">{relationships.length}</p></div><div className="panel p-4"><p className="text-xs font-semibold text-[var(--muted)]">Privileged paths</p><p className={`mt-2 text-2xl font-semibold ${privileged ? "text-red-700" : "text-[var(--navy)]"}`}>{privileged}</p></div><div className="panel p-4"><p className="text-xs font-semibold text-[var(--muted)]">Identities with mapped access</p><p className="mt-2 text-2xl font-semibold text-[var(--navy)]">{connectedIdentities}<span className="text-sm font-normal text-[var(--muted)]"> / {identities.length}</span></p></div></div>
    <div className="mt-6 rounded-lg border border-sky-200 bg-sky-50 p-4 text-sm text-sky-950"><strong>{observed} relationship{observed === 1 ? "" : "s"} automatically surfaced from observed import data.</strong> Complete inventory CSV rows that include both an identity and resource create or refresh the matching access path—no manual linking required.</div>
    {relationships.length === 0 ? <div className="panel mt-6 p-8"><h3 className="text-xl font-semibold text-[var(--navy)]">No access relationships recorded</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">Import the complete security inventory format with resource and permission columns. NHI Shield will connect matching provider records automatically.</p>{canManage && <Link className="button-primary focus-ring mt-5 inline-block" href="/import">Import complete inventory</Link>}</div> : <div className="mt-6 space-y-3">{relationships.map((relationship) => { const evidence = relationship.provenance === "observed" || relationship.source === "csv_import" || relationship.source === "connector" ? "Observed" : relationship.provenance === "derived" ? "Derived" : "User-confirmed"; return <article className="panel grid gap-4 p-5 md:grid-cols-[1fr_auto_1fr_auto] md:items-center" key={relationship.id}><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--muted)]">Identity</p><strong className="mt-1 block text-[var(--navy)]">{relationship.machine_identities?.name ?? "Identity name unavailable"}</strong><p className="mt-1 text-xs capitalize text-[var(--muted)]">{relationship.machine_identities?.privilege_level ?? "Privilege not recorded"} identity privilege</p></div><div className="rounded-lg bg-slate-100 px-4 py-2 text-center"><p className="text-[10px] font-bold uppercase text-[var(--muted)]">Can access</p><p className="mt-1 text-sm font-semibold text-[var(--teal)]">{relationship.access_level}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[var(--muted)]">Resource</p><strong className="mt-1 block text-[var(--navy)]">{relationship.resources?.name ?? "Resource name unavailable"}</strong><p className="mt-1 text-xs capitalize text-[var(--muted)]">{relationship.resources?.resource_type?.replaceAll("_", " ") ?? "Resource"} · {relationship.resources?.sensitivity ?? "Unknown"} sensitivity</p></div><div className="flex flex-wrap gap-2 md:max-w-32 md:justify-end"><span className="rounded-full bg-sky-50 px-2.5 py-1 text-xs font-semibold text-sky-800">{evidence}</span>{relationship.privileged && <span className="rounded-full bg-red-100 px-2.5 py-1 text-xs font-semibold text-red-800">Privileged</span>}{relationship.last_observed_at && <span className="text-[10px] text-[var(--muted)]">Seen {new Date(relationship.last_observed_at).toLocaleDateString()}</span>}</div></article>; })}</div>}
    <div className="panel mt-6 grid gap-4 p-5 text-xs leading-5 text-[var(--muted)] sm:grid-cols-3"><p><strong className="block text-[var(--navy)]">Observed</strong>Reported by an import or connector and time-stamped where available.</p><p><strong className="block text-[var(--navy)]">Derived</strong>Inferred by transparent NHI Shield analysis from recorded evidence.</p><p><strong className="block text-[var(--navy)]">User-confirmed</strong>Entered or explicitly verified by an authorised member.</p></div>
    {canManage && <div className="mt-8 grid gap-6 lg:grid-cols-2"><details className="panel p-6"><summary className="cursor-pointer text-lg font-semibold text-[var(--navy)]">Register one resource manually</summary><div className="mt-6"><ResourceForm/></div></details><details className="panel p-6"><summary className="cursor-pointer text-lg font-semibold text-[var(--navy)]">Confirm one relationship manually</summary>{identityOptions.length === 0 || resourceOptions.length === 0 ? <p className="mt-4 text-sm leading-6 text-[var(--muted)]">Register at least one identity and resource first.</p> : <div className="mt-6"><AccessRelationshipForm identities={identityOptions} resources={resourceOptions}/></div>}</details></div>}
  </section>;
}
