"use client";

import Link from "next/link";
import { useActionState } from "react";
import { BrandMark } from "@/components/brand-mark";
import { acceptInvite, createOrganisation, type OnboardingResult } from "@/lib/security/onboarding-actions";

const initial: OnboardingResult = { ok: true };
function Feedback({ state }: { state: OnboardingResult }) { return <>{state.error && <p className="mt-4 text-sm text-red-700" role="alert">{state.error}</p>}{state.message && <p className="mt-4 border-l-2 border-[var(--teal)] bg-[var(--teal-soft)] p-3 text-sm leading-6" role="status">{state.message}</p>}{state.inviteCode && <code className="mt-3 block select-all border border-[var(--line)] bg-[#eef4f7] p-3 font-sans text-sm">{state.inviteCode}</code>}</>; }
export default function OnboardingPage() { const [createState, createAction, creating] = useActionState(createOrganisation, initial); const [joinState, joinAction, joining] = useActionState(acceptInvite, initial); return <main className="min-h-screen bg-[var(--navy)] p-6"><div className="mx-auto max-w-4xl"><BrandMark light /><div className="mt-12"><p className="font-sans text-sm font-semibold uppercase tracking-wider text-[var(--cyan)]">Workspace setup</p><h1 className="mt-3 font-serif text-5xl text-white">Set up your workspace</h1><p className="font-sans mt-5 max-w-2xl text-slate-300">Create a new organisation or join one with a secure invite code. Organisation access is never granted from a name alone.</p></div><div className="mt-10 grid gap-6 md:grid-cols-2"><section className="bg-white p-7 text-[var(--ink)]"><h2 className="font-serif text-2xl">Create an organisation</h2><p className="font-sans mt-3 text-sm leading-6 text-[var(--muted)]">You become the organisation administrator. Customers cannot assign themselves platform admin.</p><form action={createAction} className="mt-7"><label className="font-sans text-sm font-medium">Organisation name<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="name" required minLength={2} /></label><Feedback state={createState} /><button className="focus-ring mt-5 bg-[var(--teal)] px-5 py-3 font-sans text-sm font-semibold text-white" disabled={creating}>{creating ? "Creating..." : "Create organisation"}</button></form></section><section className="bg-white p-7 text-[var(--ink)]"><h2 className="font-serif text-2xl">Join an organisation</h2><p className="font-sans mt-3 text-sm leading-6 text-[var(--muted)]">Use an invite code supplied by an organisation administrator. Codes are expiring, limited-use and stored hashed.</p><form action={joinAction} className="mt-7"><label className="font-sans text-sm font-medium">Invite code<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3 uppercase" name="inviteCode" required autoComplete="off" /></label><Feedback state={joinState} /><button className="focus-ring mt-5 bg-[var(--navy)] px-5 py-3 font-sans text-sm font-semibold text-white" disabled={joining}>{joining ? "Joining..." : "Join organisation"}</button></form></section></div><Link className="focus-ring mt-8 inline-block font-sans text-sm text-slate-300" href="/sign-in">Return to sign in</Link></div></main>; }