"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/browser";
import { useRouter } from "next/navigation";
import { BrandMark } from "@/components/brand-mark";

export default function SignInPage() {
  const router = useRouter();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const { error: authError } = await createClient().auth.signInWithPassword({ email, password }); if (authError) { setError("Sign-in could not be completed. Check your credentials or contact an administrator."); setBusy(false); return; } router.push("/overview"); }
  return <main className="sans min-h-screen bg-[var(--navy)] p-6 text-white"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-5xl items-center justify-center"><section className="grid w-full overflow-hidden rounded-sm bg-white text-[var(--ink)] shadow-2xl md:grid-cols-[1.05fr_0.95fr]"><div className="bg-[#173c59] p-10 text-white md:p-14"><BrandMark light /><h1 className="mt-20 font-serif text-5xl leading-[0.95]">Machine identity security, built on trust.</h1><p className="mt-6 max-w-sm text-sm leading-6 text-slate-300">A secure command centre for the access relationships that power your organisation.</p></div><div className="p-10 md:p-14"><Link className="focus-ring text-sm text-[var(--teal)]" href="/">← Return to website</Link><p className="mt-10 text-sm font-semibold uppercase tracking-wider text-[var(--teal)]">Secure access</p><h2 className="mt-3 font-serif text-3xl">Sign in to your workspace</h2><form onSubmit={submit} className="mt-10 space-y-5"><label className="block text-sm font-medium">Work email<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" type="email" required autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="block text-sm font-medium">Password<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" type="password" required autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} /></label><div className="flex justify-end"><Link className="focus-ring text-xs text-[var(--teal)] hover:text-[var(--navy)]" href="/forgot-password">Forgot password?</Link></div>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button className="focus-ring w-full bg-[var(--teal)] px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={busy}>{busy ? "Authenticating..." : "Sign in"}</button></form><p className="mt-6 text-sm text-[var(--muted)]">New to NHI Shield? <Link className="focus-ring font-semibold text-[var(--teal)]" href="/sign-up">Create an account</Link></p><p className="mt-5 text-xs leading-5 text-[var(--muted)]">Access is provisioned by your organisation administrator. Registration does not automatically create organisation access.</p></div></section></div></main>;
}