import Link from "next/link";
import { MachineIdentityForm } from "@/components/security-forms";
import { requireSecurityContext } from "@/lib/security/context";
import { hasPermission } from "@/lib/security/permissions";
import { listMachineIdentities } from "@/lib/security/repositories";

type Props = { searchParams: Promise<{ q?: string; view?: string }> };
const sourceLabel: Record<string, string> = { csv_import: "Observed · CSV", connector: "Observed · connector", manual: "User-confirmed" };
export default async function MachineIdentitiesPage({ searchParams }: Props) {
  const context = await requireSecurityContext("view_security_data"); const identities = await listMachineIdentities(context); const params = await searchParams; const query = (params.q ?? "").trim().toLowerCase(); const view = params.view ?? "all"; const searched = query ? identities.filter((identity) => [identity.name, identity.provider, identity.owner_name, identity.identity_type].some((value) => value?.toLowerCase().includes(query))) : identities; const filtered = view === "unowned" ? searched.filter((identity) => !identity.owner_name) : view === "privileged" ? searched.filter((identity) => identity.privilege_level === "high" || identity.privilege_level === "critical") : view === "conflicts" ? searched.filter((identity) => identity.ownership_conflict) : searched; const canManage = hasPermission(context.role, "manage_security_inventory"); const unowned = identities.filter((identity) => !identity.owner_name).length; const privileged = identities.filter((identity) => identity.privilege_level === "high" || identity.privilege_level === "critical").length; const conflicts = identities.filter((identity) => identity.ownership_conflict).length;
  return <section><div className="flex flex-col gap-5 border-b border-[var(--line)] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--teal)]">Discover · Identity inventory</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-[var(--navy)] sm:text-4xl">Apps & system accounts</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">Understand every non-human identity, where it runs, who owns it and how the record entered NHI Shield.</p></div>{canManage && <Link className="button-primary focus-ring text-center" href="/import">Import inventory</Link>}</div>
    <div className="mt-6 grid gap-3 sm:grid-cols-3">{[["All identities", identities.length, "all"], ["Missing owners", unowned, "unowned"], ["High privilege", privileged, "privileged"]].map(([label, value, key]) => <Link className={`panel focus-ring p-4 ${view === key ? "border-[var(--teal)] ring-1 ring-[var(--teal)]" : ""}`} href={`/machine-identities?view=${key}`} key={key}><p className="text-xs font-semibold text-[var(--muted)]">{label}</p><p className="mt-2 text-2xl font-semibold text-[var(--navy)]">{value}</p></Link>)}</div>{conflicts > 0 && <Link className="mt-3 block rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950" href="/machine-identities?view=conflicts"><strong>{conflicts} ownership conflict{conflicts === 1 ? "" : "s"} detected.</strong> The same provider identity was imported with different owners. Review and confirm the accountable team.</Link>}
    <div className="mt-6 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><form className="flex max-w-xl flex-1 gap-3" method="get"><input name="view" type="hidden" value={view}/><label className="sr-only" htmlFor="identity-search">Search machine identities</label><input className="focus-ring min-w-0 flex-1 rounded-lg border border-[var(--line)] bg-white px-3 py-3 text-sm" defaultValue={query} id="identity-search" name="q" placeholder="Search name, provider, type or owner"/><button className="focus-ring rounded-lg border border-[var(--navy)] px-4 py-3 text-sm font-semibold text-[var(--navy)]">Search</button></form><p className="text-sm text-[var(--muted)]">{filtered.length} matching record{filtered.length === 1 ? "" : "s"}</p></div>
    {filtered.length === 0 ? <div className="panel mt-6 p-8"><h3 className="text-xl font-semibold text-[var(--navy)]">{query || view !== "all" ? "No matching identities" : "No machine identities recorded"}</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">{query || view !== "all" ? "Change the search or inventory filter." : "Import a complete security inventory to discover identities, resources and access relationships together."}</p></div> : <div className="panel mt-6 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-[var(--line)] bg-slate-50 text-[10px] uppercase tracking-[.12em] text-[var(--muted)]"><tr><th className="px-5 py-4">Identity</th><th className="px-5 py-4">Context</th><th className="px-5 py-4">Owner</th><th className="px-5 py-4">Privilege</th><th className="px-5 py-4">Evidence</th><th className="px-5 py-4">Status</th></tr></thead><tbody>{filtered.map((identity) => <tr className="border-b border-[var(--line)] last:border-0 hover:bg-slate-50/70" key={identity.id}><td className="px-5 py-4"><Link className="focus-ring font-semibold text-[var(--navy)] hover:text-[var(--teal)]" href={`/machine-identities/${identity.id}`}>{identity.name}</Link><p className="mt-1 text-xs capitalize text-[var(--muted)]">{identity.identity_type.replaceAll("_", " ")}</p></td><td className="px-5 py-4"><p>{identity.provider ?? "Provider not recorded"}</p><p className="mt-1 text-xs capitalize text-[var(--muted)]">{identity.environment}</p></td><td className="px-5 py-4">{identity.owner_name ? <><p>{identity.owner_name}</p>{identity.owner_email && <p className="mt-1 text-xs text-[var(--muted)]">{identity.owner_email}</p>}</> : <span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-semibold text-amber-800">Owner needed</span>}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${identity.privilege_level === "critical" || identity.privilege_level === "high" ? "bg-red-100 text-red-800" : "bg-slate-100 text-slate-700"}`}>{identity.privilege_level}</span></td><td className="px-5 py-4"><span className="rounded-full bg-sky-50 px-2.5 py-1 text-xs font-semibold text-sky-800">{sourceLabel[identity.source_type] ?? "Recorded"}</span>{identity.last_seen_at && <p className="mt-2 text-xs text-[var(--muted)]">Seen {new Date(identity.last_seen_at).toLocaleDateString()}</p>}</td><td className="px-5 py-4 capitalize">{identity.status}</td></tr>)}</tbody></table></div></div>}
    <div className="panel mt-6 grid gap-4 p-5 text-xs leading-5 text-[var(--muted)] sm:grid-cols-3"><p><strong className="block text-[var(--navy)]">Observed</strong>Directly supplied by a CSV or connector, with its source retained.</p><p><strong className="block text-[var(--navy)]">Derived</strong>Calculated by NHI Shield rules from recorded facts; not claimed as a direct observation.</p><p><strong className="block text-[var(--navy)]">User-confirmed</strong>Entered or reviewed by an authorised workspace member.</p></div>
    {canManage && <details className="panel mt-8 p-6"><summary className="cursor-pointer text-lg font-semibold text-[var(--navy)]">Register one identity manually</summary><p className="mt-3 text-sm leading-6 text-[var(--muted)]">For multiple identities, use the complete inventory CSV to reduce manual work and discover relationships at the same time.</p><div className="mt-6"><MachineIdentityForm/></div></details>}
  </section>;
}
