"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { BrandMark } from "@/components/brand-mark";
import { createClient } from "@/lib/supabase/browser";
import { recoverySchema } from "@/lib/validation/auth";

export default function ForgotPasswordPage() { const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setMessage(null); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const result = recoverySchema.safeParse(values); if (!result.success) { setError(result.error.issues[0]?.message ?? "Enter a valid email."); return; } setBusy(true); const { error: authError } = await createClient().auth.resetPasswordForEmail(result.data.email, { redirectTo: `${window.location.origin}/sign-in` }); if (authError) setError("The recovery request could not be completed. Try again or contact an administrator."); else setMessage("If an account matches that email, recovery instructions will be sent according to the Supabase Auth configuration."); setBusy(false); }
  return <main className="sans min-h-screen bg-[var(--navy)] p-6 text-white"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-2xl items-center justify-center"><section className="w-full rounded-sm bg-white p-10 text-[var(--ink)] shadow-2xl md:p-14"><BrandMark /><Link className="focus-ring mt-10 inline-block text-sm text-[var(--teal)]" href="/sign-in">← Back to sign in</Link><p className="mt-10 text-sm font-semibold uppercase tracking-wider text-[var(--teal)]">Account recovery</p><h1 className="mt-3 font-serif text-4xl">Reset your password</h1><p className="sans mt-5 text-sm leading-6 text-[var(--muted)]">Enter your account email and Supabase Auth will handle the recovery message when configured.</p><form onSubmit={submit} className="sans mt-8 space-y-5"><label className="block text-sm font-medium">Work email<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="email" type="email" required autoComplete="email" /></label>{error && <p className="text-sm text-red-700" role="alert">{error}</p>}{message && <p className="border-l-2 border-[var(--teal)] bg-[var(--teal-soft)] p-4 text-sm leading-6" role="status">{message}</p>}<button className="focus-ring w-full bg-[var(--teal)] px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={busy}>{busy ? "Sending..." : "Send recovery email"}</button></form></section></div></main>; }