"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { askSecurityAnalyst } from "@/lib/security/ai-actions";
import type { AiResult } from "@/lib/security/ai-types";

const initial: AiResult = { ok: true, configured: true };
const suggestions = ["Which machine identities have the highest deterministic risk?", "Show privileged access to critical resources.", "Which credential metadata is expired or expiring?", "Explain recent suspicious activity and open incidents.", "What should be investigated first?", "How do I import security inventory data?"];
export function AiAnalystConsole() {
  const [state, action, pending] = useActionState(askSecurityAnalyst, initial); const [question, setQuestion] = useState(""); const answer = state.answer;
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
    <section className="panel overflow-hidden"><form action={action} className="border-b border-[var(--line)] p-5 sm:p-6"><label className="text-xs font-bold uppercase tracking-[.16em] text-[var(--teal)]" htmlFor="ai-question">Investigation question</label><textarea className="focus-ring mt-3 min-h-28 w-full rounded-lg border border-[var(--line)] p-3 text-sm" id="ai-question" maxLength={1200} name="question" onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about tenant-scoped NHI risk, findings, incidents, evidence, access, credentials, or activity." required value={question}/><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-[var(--muted)]">Read-only analysis · no remediation execution</p><button className="button-primary" disabled={pending} type="submit">{pending ? "Analysing…" : "Analyse"}</button></div></form>
      <div aria-live="polite" className="p-5 sm:p-6">{state.error && <div className="border-l-4 border-amber-600 bg-amber-50 p-4 text-sm text-amber-950" role="alert">{state.error}</div>}{!answer && !state.error && <p className="text-sm text-[var(--muted)]">Submit a question to analyse authorised NHI Shield records.</p>}{answer && <div className="space-y-7"><section><h2 className="text-lg font-semibold text-[var(--navy)]">Answer</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{answer.interpretation}</p></section><FactSection title="Deterministic NHI Shield assessment" items={answer.deterministicAssessment}/><FactSection title="Persisted facts" items={answer.facts}/>{answer.recommendations.length > 0 && <section><h2 className="text-sm font-bold uppercase tracking-[.14em] text-[var(--navy)]">Investigation priorities</h2><ol className="mt-3 space-y-2 text-sm">{answer.recommendations.map((item, index) => <li className="flex gap-3" key={item}><span className="font-bold text-[var(--teal)]">{index + 1}</span><span>{item}</span></li>)}</ol></section>}<section><h2 className="text-sm font-bold uppercase tracking-[.14em] text-[var(--navy)]">Evidence / References</h2>{answer.references.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{answer.references.map((item) => item.route ? <Link className="focus-ring rounded-lg border border-[var(--line)] p-3 text-sm hover:bg-[#eef4f7]" href={item.route} key={item.key}><span className="block text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">{item.kind.replaceAll("_", " ")}</span><span className="mt-1 block font-semibold text-[var(--teal)]">{item.label}</span><span className="mt-1 block font-mono text-[10px] text-[var(--muted)]">{item.id}</span></Link> : <div className="rounded-lg border border-[var(--line)] p-3 text-sm" key={item.key}><span className="block text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">{item.kind.replaceAll("_", " ")}</span><span className="mt-1 block font-semibold">{item.label}</span><span className="mt-1 block font-mono text-[10px] text-[var(--muted)]">{item.id}</span></div>)}</div> : <p className="mt-3 text-sm text-[var(--muted)]">No matching evidence records were returned.</p>}</section><div className="border-t border-[var(--line)] pt-4 text-xs text-[var(--muted)]">{answer.limitations.map((item) => <p key={item}>{item}</p>)}</div></div>}</div>
    </section>
    <aside className="space-y-6"><section className="panel p-5"><h2 className="text-sm font-bold uppercase tracking-[.14em] text-[var(--navy)]">Suggested investigations</h2><div className="mt-3 space-y-2">{suggestions.map((item) => <button className="focus-ring w-full rounded-lg border border-[var(--line)] p-3 text-left text-xs font-semibold text-[var(--navy)] hover:bg-[#eef4f7]" key={item} onClick={() => setQuestion(item)} type="button">{item}</button>)}</div></section>{answer?.actions?.length ? <section className="panel p-5"><h2 className="text-sm font-bold uppercase tracking-[.14em] text-[var(--navy)]">Contextual navigation</h2><div className="mt-3 space-y-2">{answer.actions.map((item) => <Link className="focus-ring block rounded-lg bg-[var(--teal)] px-4 py-3 text-center text-xs font-semibold text-white" href={item.href} key={item.href}>{item.label}</Link>)}</div></section> : null}</aside>
  </div>;
}
function FactSection({ title, items }: { title: string; items: Array<{ text: string; referenceKeys: string[] }> }) { if (!items.length) return null; return <section><h2 className="text-sm font-bold uppercase tracking-[.14em] text-[var(--navy)]">{title}</h2><ul className="mt-3 space-y-2 text-sm leading-6">{items.map((item) => <li className="rounded-lg bg-[#f4f8f9] px-4 py-3" key={`${item.text}-${item.referenceKeys.join()}`}>{item.text}<span className="mt-1 block font-mono text-[10px] text-[var(--muted)]">{item.referenceKeys.join(", ")}</span></li>)}</ul></section>; }
