"use client";

import Link from "next/link";
import { useActionState, useMemo, useRef, useState } from "react";
import { csvSamples, detectedColumnMappings, type ImportEntity, validateCsv } from "@/lib/security/csv-import";
import { importCsv, type ImportResult } from "@/lib/security/import-actions";

const initial: ImportResult = { ok: true };
const labels: Record<ImportEntity, string> = { security_inventory: "Complete security inventory (recommended)", machine_identities: "Apps & system accounts only", resources: "Company resources only", access_relationships: "Who can access what", credentials: "Credential metadata (never secrets)" };
function fileSize(bytes: number) { return bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(bytes < 10240 ? 1 : 0)} KB`; }

export function CsvImportForm() {
  const [entity, setEntity] = useState<ImportEntity>("security_inventory"); const [csv, setCsv] = useState(""); const [fileName, setFileName] = useState(""); const [selectedSize, setSelectedSize] = useState(0); const [previewed, setPreviewed] = useState(false); const [clientError, setClientError] = useState(""); const [dragging, setDragging] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const [state, action, pending] = useActionState(importCsv, initial);
  const preview = useMemo(() => { if (!previewed || !csv) return []; try { return validateCsv(entity, csv); } catch (error) { return [{ row: 0, values: {}, valid: false, errors: [error instanceof Error ? error.message : "This file could not be read."] }]; } }, [csv, entity, previewed]);
  const mappings = useMemo(() => { if (!previewed || !csv) return []; try { return detectedColumnMappings(csv); } catch { return []; } }, [csv, previewed]);
  const invalidCount = preview.filter((row) => !row.valid).length; const headers = preview[0] ? Object.keys(preview[0].values) : [];
  function reset(nextEntity = entity) { setEntity(nextEntity); setCsv(""); setFileName(""); setSelectedSize(0); setPreviewed(false); setClientError(""); if (inputRef.current) inputRef.current.value = ""; }
  async function selectFile(file?: File) {
    if (!file) return; setClientError(""); setPreviewed(false); setCsv(""); setFileName(""); setSelectedSize(0);
    const lowerName = file.name.toLowerCase();
    if (lowerName.endsWith(".xlsx") || lowerName.endsWith(".xls")) { setClientError("Excel workbooks are not supported. In Excel, choose Save As or Export and select CSV (.csv), then upload that file."); return; }
    if (!lowerName.endsWith(".csv")) { setClientError("That file is not a CSV. Choose a file whose name ends in .csv."); return; }
    if (file.size > 1_000_000) { setClientError("This file is larger than 1 MB. Split it into smaller CSV files."); return; }
    if (file.size === 0) { setClientError("This CSV is empty. Add a header row and at least one data row."); return; }
    try { const text = await file.text(); validateCsv(entity, text); setCsv(text); setFileName(file.name); setSelectedSize(file.size); } catch (error) { setClientError(error instanceof Error ? error.message : "This file is not a valid CSV."); }
  }
  function downloadTemplate() { const blob = new Blob([csvSamples[entity]], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `nhi-shield-${entity.replaceAll("_", "-")}-demo.csv`; link.click(); URL.revokeObjectURL(link.href); }

  return <form action={action} className="panel space-y-6 p-4 sm:p-6" aria-busy={pending}>
    <div><label className="text-sm font-semibold" htmlFor="import-type">What are you adding?</label><select id="import-type" className="focus-ring mt-2 w-full rounded-lg border border-[var(--line)] bg-white px-3 py-3 text-sm" name="entity" value={entity} onChange={(event) => reset(event.target.value as ImportEntity)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><p className="mt-2 text-sm leading-6 text-[var(--muted)]">The recommended format discovers identities, resources, credential metadata and their access relationships together using provider reference IDs—not database UUIDs.</p></div>
    <div className={`rounded-xl border-2 border-dashed p-6 text-center transition ${dragging ? "border-[var(--teal)] bg-[var(--teal-soft)]" : "border-[var(--line)] bg-slate-50"}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={(event) => { if (event.currentTarget === event.target) setDragging(false); }} onDrop={(event) => { event.preventDefault(); setDragging(false); void selectFile(event.dataTransfer.files[0]); }}>
      <div className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-white text-xl text-[var(--teal)] shadow-sm">↑</div><label className="mt-3 block text-sm font-semibold text-[var(--navy)]" htmlFor="csv-file">Drop a CSV here, or choose a file</label><p className="mt-1 text-xs text-[var(--muted)]">CSV (.csv) only · up to 1 MB and 1,000 rows</p><input accept=".csv" className="focus-ring mx-auto mt-4 block max-w-full text-sm file:mr-3 file:rounded-md file:border-0 file:bg-[var(--navy)] file:px-4 file:py-2.5 file:font-semibold file:text-white" id="csv-file" onChange={(event) => void selectFile(event.target.files?.[0])} ref={inputRef} type="file" />
      <div className="mt-5 border-t border-[var(--line)] pt-4"><button className="focus-ring rounded-lg border border-[var(--line)] bg-white px-4 py-2.5 text-sm font-semibold text-[var(--navy)]" onClick={downloadTemplate} type="button">Download example CSV</button><p className="mt-2 text-xs text-[var(--muted)]">Have an Excel file? Export or save it as CSV first.</p></div>
    </div>
    {fileName && <div className="flex flex-col gap-4 rounded-lg border border-emerald-200 bg-emerald-50 p-4 sm:flex-row sm:items-center sm:justify-between" role="status"><div className="min-w-0"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-emerald-600 text-xs font-bold text-white">✓</span><p className="truncate text-sm font-semibold text-emerald-950">{fileName}</p></div><p className="ml-8 mt-1 text-xs text-emerald-800">{fileSize(selectedSize)} · CSV format · ready to preview</p></div><div className="flex shrink-0 gap-2"><button className="focus-ring rounded-lg px-3 py-2 text-xs font-semibold text-[var(--muted)]" onClick={() => reset()} type="button">Remove</button><button className="focus-ring rounded-lg bg-[var(--navy)] px-4 py-2.5 text-sm font-semibold text-white" onClick={() => setPreviewed(true)} type="button">Validate and preview</button></div></div>}
    {clientError && <p className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800" role="alert"><strong>File not accepted.</strong> {clientError}</p>}
    <p className="text-xs leading-5 text-[var(--muted)]">Passwords, secret values, tokens, private keys and client secrets are always rejected. File contents are validated again securely when you confirm the import.</p>
    {previewed && preview.length > 0 && <section aria-labelledby="preview-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--teal)]">Validation result</p><h3 className="mt-2 text-xl font-semibold text-[var(--navy)]" id="preview-heading">Review before importing</h3></div><p className="text-sm text-[var(--muted)]">{preview.length} rows · <span className="font-semibold text-emerald-700">{preview.length - invalidCount} ready</span> · <span className={invalidCount ? "font-semibold text-red-700" : ""}>{invalidCount} need attention</span></p></div><details className="mt-4 rounded-lg border border-[var(--line)] bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-semibold">Detected column mapping ({mappings.length} columns)</summary><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-3">{mappings.map((mapping) => <p key={mapping.uploaded}><span className="font-mono">{mapping.uploaded}</span> → <span className="font-mono">{mapping.mappedTo}</span>{mapping.automatic && <span className="ml-1 text-[var(--teal)]">auto-mapped</span>}</p>)}</div></details><div className="mt-4 max-h-96 overflow-auto rounded-lg border border-[var(--line)]"><table className="min-w-full text-left text-xs"><thead className="sticky top-0 bg-[var(--navy)] text-white"><tr><th className="p-3">Row</th><th className="p-3">Status</th>{headers.slice(0, 5).map((header) => <th className="p-3" key={header}>{header.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{preview.slice(0, 100).map((row) => <tr className="border-t border-[var(--line)] align-top" key={row.row}><td className="p-3">{row.row || "—"}</td><td className={`p-3 font-semibold ${row.valid ? "text-emerald-700" : "text-red-700"}`}>{row.valid ? "Ready" : row.errors.join(" ")}</td>{headers.slice(0, 5).map((header) => <td className="max-w-48 truncate p-3" key={header} title={row.values[header]}>{row.values[header] || "—"}</td>)}</tr>)}</tbody></table></div>{preview.length > 100 && <p className="mt-2 text-xs text-[var(--muted)]">Showing the first 100 rows. All {preview.length} rows will be validated.</p>}</section>}
    <input name="csv" type="hidden" value={csv} /><input name="confirmed" type="hidden" value={previewed && invalidCount === 0 ? "yes" : "no"} />
    {state.errors?.map((error) => <p className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800" key={error} role="alert">{error}</p>)}{state.message && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-950" role="status"><p className="font-semibold">{state.message}</p><div className="mt-4 flex flex-wrap gap-2"><Link className="focus-ring rounded-lg bg-[var(--teal)] px-4 py-2.5 text-xs font-semibold text-white" href="/overview">Run or review analysis</Link><Link className="focus-ring rounded-lg border border-emerald-300 bg-white px-4 py-2.5 text-xs font-semibold" href="/machine-identities">Review imported identities</Link><Link className="focus-ring rounded-lg border border-emerald-300 bg-white px-4 py-2.5 text-xs font-semibold" href="/data-sources">View import history</Link></div></div>}
    {previewed && invalidCount === 0 && !state.message && <div className="rounded-lg border-2 border-[var(--teal)] bg-[var(--teal-soft)] p-5"><p className="text-sm font-semibold text-[var(--navy)]">Import {preview.length} validated row{preview.length === 1 ? "" : "s"}?</p><p className="mt-2 text-xs leading-5 text-[var(--muted)]">The import is atomic: every row is saved, or no rows are saved.</p><button className="focus-ring mt-4 rounded-lg bg-[var(--teal)] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60" disabled={pending}>{pending ? "Importing…" : "Confirm import"}</button></div>}
  </form>;
}
