"use client";

import { useActionState, useMemo, useState } from "react";
import { csvSamples, detectedColumnMappings, type ImportEntity, validateCsv } from "@/lib/security/csv-import";
import { importCsv, type ImportResult } from "@/lib/security/import-actions";

const initial: ImportResult = { ok: true };
const labels: Record<ImportEntity, string> = { security_inventory: "Complete security inventory (recommended)", machine_identities: "Apps & system accounts only", resources: "Company resources only", access_relationships: "Who can access what", credentials: "Credential metadata (never secrets)" };

export function CsvImportForm() {
  const [entity, setEntity] = useState<ImportEntity>("security_inventory");
  const [csv, setCsv] = useState(""); const [fileName, setFileName] = useState(""); const [previewed, setPreviewed] = useState(false); const [clientError, setClientError] = useState("");
  const [state, action, pending] = useActionState(importCsv, initial);
  const preview = useMemo(() => { if (!previewed || !csv) return []; try { return validateCsv(entity, csv); } catch (error) { return [{ row: 0, values: {}, valid: false, errors: [error instanceof Error ? error.message : "This file could not be read."] }]; } }, [csv, entity, previewed]);
  const mappings = useMemo(() => { if (!previewed || !csv) return []; try { return detectedColumnMappings(csv); } catch { return []; } }, [csv, previewed]);
  const invalidCount = preview.filter((row) => !row.valid).length; const headers = preview[0] ? Object.keys(preview[0].values) : [];
  function reset(nextEntity = entity) { setEntity(nextEntity); setCsv(""); setFileName(""); setPreviewed(false); setClientError(""); }
  async function selectFile(file?: File) { if (!file) return; setClientError(""); if (!file.name.toLowerCase().endsWith(".csv")) { setClientError("Choose a file ending in .csv."); return; } if (file.size > 1_000_000) { setClientError("This file is larger than 1 MB. Split it into smaller files."); return; } setCsv(await file.text()); setFileName(file.name); setPreviewed(false); }
  function downloadTemplate() { const blob = new Blob([csvSamples[entity]], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `nhi-shield-${entity.replaceAll("_", "-")}-demo.csv`; link.click(); URL.revokeObjectURL(link.href); }

  return <form action={action} className="space-y-6 border border-[var(--line)] bg-white p-4 sm:p-6" aria-busy={pending}>
    <div><label className="font-sans text-sm font-semibold" htmlFor="import-type">What are you adding?</label><select id="import-type" className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="entity" value={entity} onChange={(event) => reset(event.target.value as ImportEntity)}>{Object.entries(labels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select><p className="mt-2 text-sm text-[var(--muted)]">The recommended file maps accounts, resources, credential metadata, and access in one transaction using provider reference IDs—not database IDs.</p></div>
    <div className="rounded border border-dashed border-[var(--line)] bg-[#f7fafb] p-5"><label className="block font-sans text-sm font-semibold" htmlFor="csv-file">Choose a CSV file</label><input accept=".csv,text/csv" className="focus-ring mt-3 block w-full text-sm" id="csv-file" onChange={(event) => void selectFile(event.target.files?.[0])} type="file"/><button className="focus-ring mt-4 border border-[var(--line)] bg-white px-4 py-2 text-sm font-semibold" onClick={downloadTemplate} type="button">Download realistic demo CSV</button><p className="mt-3 text-xs leading-5 text-[var(--muted)]">Up to 1 MB or 1,000 rows. Passwords, secret values, tokens, private keys, and client secrets are always rejected.</p></div>
    {fileName && <div className="flex flex-wrap items-center justify-between gap-3" role="status"><p className="text-sm"><strong>Selected:</strong> {fileName}</p><button className="focus-ring bg-[var(--navy)] px-5 py-3 text-sm font-semibold text-white" onClick={() => setPreviewed(true)} type="button">Check and preview file</button></div>}
    {clientError && <p className="border-l-4 border-red-600 bg-red-50 p-3 text-sm text-red-800" role="alert">{clientError}</p>}
    {previewed && preview.length > 0 && <section aria-labelledby="preview-heading"><h3 className="font-serif text-xl" id="preview-heading">Review before importing</h3><p className="mt-1 text-sm text-[var(--muted)]">{preview.length} rows checked · {preview.length-invalidCount} ready · {invalidCount} need attention</p><details className="mt-4 border border-[var(--line)] bg-[#f7fafb] p-4"><summary className="cursor-pointer text-sm font-semibold">Detected column mapping ({mappings.length} columns)</summary><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-3">{mappings.map((mapping) => <p key={mapping.uploaded}><span className="font-mono">{mapping.uploaded}</span> → <span className="font-mono">{mapping.mappedTo}</span>{mapping.automatic && <span className="ml-1 text-[var(--teal)]">auto-mapped</span>}</p>)}</div></details><div className="mt-4 max-h-96 overflow-auto border border-[var(--line)]"><table className="min-w-full text-left text-xs"><thead className="sticky top-0 bg-[var(--navy)] text-white"><tr><th className="p-3">Row</th><th className="p-3">Status</th>{headers.slice(0,5).map((header) => <th className="p-3" key={header}>{header.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{preview.slice(0,100).map((row) => <tr className="border-t border-[var(--line)] align-top" key={row.row}><td className="p-3">{row.row || "—"}</td><td className={`p-3 font-semibold ${row.valid ? "text-emerald-700" : "text-red-700"}`}>{row.valid ? "Ready" : row.errors.join(" ")}</td>{headers.slice(0,5).map((header) => <td className="max-w-48 truncate p-3" key={header} title={row.values[header]}>{row.values[header] || "—"}</td>)}</tr>)}</tbody></table></div>{preview.length > 100 && <p className="mt-2 text-xs text-[var(--muted)]">Showing the first 100 rows. All {preview.length} rows will be validated.</p>}</section>}
    <input name="csv" type="hidden" value={csv}/><input name="confirmed" type="hidden" value={previewed && invalidCount === 0 ? "yes" : "no"}/>
    {state.errors?.map((error) => <p className="border-l-4 border-red-600 bg-red-50 p-3 text-sm text-red-800" key={error} role="alert">{error}</p>)}{state.message && <p className="border-l-4 border-[var(--teal)] bg-[var(--teal-soft)] p-3 text-sm" role="status">{state.message}</p>}
    {previewed && invalidCount === 0 && <div className="border-t border-[var(--line)] pt-5"><p className="text-sm font-semibold">Ready to add {preview.length} rows to this company?</p><p className="mt-1 text-xs text-[var(--muted)]">Matching provider reference IDs will be updated; other records will be created. Imported facts are labelled observed. The whole file succeeds or nothing is saved.</p><button className="focus-ring mt-4 bg-[var(--teal)] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60" disabled={pending}>{pending ? "Importing securely…" : "Confirm and import"}</button></div>}
  </form>;
}
