"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { BrandMark } from "@/components/brand-mark";
import type { Role } from "@/lib/security/permissions";

type Membership = { role: Role; organisationName: string } | null;
type Props = { children: React.ReactNode; email: string; membership: Membership };
type NavItem = { label: string; shortLabel?: string; href: string; glyph: string; mutate?: boolean; admin?: boolean };

const groups: Array<{ label: string; description: string; items: NavItem[] }> = [
  { label: "Monitor", description: "Current security posture", items: [{ label: "Security overview", shortLabel: "Overview", href: "/overview", glyph: "01" }, { label: "Risks & findings", shortLabel: "Risks", href: "/findings", glyph: "02" }, { label: "Incidents", href: "/incidents", glyph: "03" }] },
  { label: "Discover", description: "Inventory and access", items: [{ label: "Identity inventory", shortLabel: "Inventory", href: "/machine-identities", glyph: "04" }, { label: "Access relationships", shortLabel: "Relationships", href: "/access-graph", glyph: "05" }, { label: "Import company data", shortLabel: "Import", href: "/import", glyph: "06", mutate: true }, { label: "Data sources", href: "/data-sources", glyph: "07", mutate: true }] },
  { label: "Respond", description: "Investigate and reduce risk", items: [{ label: "Ask NHI Shield AI", shortLabel: "AI Analyst", href: "/ai-analyst", glyph: "AI" }, { label: "Recommended actions", shortLabel: "Remediation", href: "/remediation", glyph: "08" }, { label: "Reports", href: "/reports", glyph: "09" }, { label: "Audit history", href: "/audit-log", glyph: "10" }] },
];

const roleLabels: Record<Role, string> = { platform_admin: "Platform administrator", organisation_admin: "Organisation administrator", security_analyst: "Security analyst", viewer: "Viewer · read only" };
const settings: NavItem = { label: "Settings & members", shortLabel: "Settings", href: "/settings", glyph: "11", admin: true };
function permitted(item: NavItem, role?: Role) { return !(role === "viewer" && item.mutate) && !(item.admin && !(["organisation_admin", "platform_admin"] as Role[]).includes(role!)); }
function isActive(pathname: string, href: string) { return pathname === href || (href !== "/overview" && pathname.startsWith(`${href}/`)); }

function Nav({ pathname, role, onNavigate }: { pathname: string; role?: Role; onNavigate?: () => void }) {
  return <nav aria-label="Primary navigation" className="space-y-7">{groups.map((group) => { const items = group.items.filter((item) => permitted(item, role)); if (!items.length) return null; return <section key={group.label}><div className="px-3"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-slate-400">{group.label}</p><p className="mt-1 text-[11px] text-slate-500">{group.description}</p></div><div className="mt-2 space-y-1">{items.map((item) => <Link aria-current={isActive(pathname, item.href) ? "page" : undefined} className={`focus-ring group flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${isActive(pathname, item.href) ? "bg-white/10 font-semibold text-white shadow-[inset_3px_0_0_var(--cyan)]" : "text-slate-300 hover:bg-white/5 hover:text-white"}`} href={item.href} key={item.href} onClick={onNavigate}><span className={`flex h-7 w-7 items-center justify-center rounded-md border text-[9px] font-bold tracking-wider ${isActive(pathname, item.href) ? "border-[var(--cyan)] bg-[var(--cyan)]/10 text-[var(--cyan)]" : "border-slate-600 text-slate-500 group-hover:border-slate-400"}`}>{item.glyph}</span>{item.shortLabel ?? item.label}</Link>)}</div></section>; })}</nav>;
}

function Account({ email, membership }: { email: string; membership: Membership }) { return <div className="border-t border-white/10 p-4"><div className="rounded-lg bg-white/5 p-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[var(--cyan)]/15 text-xs font-bold text-[var(--cyan)]">{email.slice(0, 1).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-xs font-semibold text-white">{email}</p>{membership && <p className="mt-0.5 truncate text-[11px] text-slate-400">{roleLabels[membership.role]}</p>}</div></div></div>{permitted(settings, membership?.role) && <Link className="focus-ring mt-2 flex items-center gap-3 rounded-lg px-3 py-2 text-xs text-slate-300 hover:bg-white/5 hover:text-white" href={settings.href}><span className="text-slate-500">{settings.glyph}</span>{settings.shortLabel}</Link>}<form action="/auth/signout" method="post"><button className="focus-ring mt-1 w-full rounded-lg px-3 py-2 text-left text-xs font-semibold text-slate-400 hover:bg-white/5 hover:text-white">Sign out</button></form></div>; }

export function ProtectedShell({ children, email, membership }: Props) {
  const pathname = usePathname(); const [open, setOpen] = useState(false);
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [open]);
  const allItems = [...groups.flatMap((group) => group.items), settings]; const current = allItems.find((item) => isActive(pathname, item.href))?.label ?? "Security workspace";
  const sidebar = <><div className="border-b border-white/10 px-5 py-5"><BrandMark light />{membership && <div className="mt-5 rounded-lg border border-white/10 bg-white/5 px-3 py-2.5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Protected workspace</p><p className="mt-1 truncate text-sm font-semibold text-white">{membership.organisationName}</p></div>}</div><div className="flex-1 overflow-y-auto px-3 py-6"><Nav pathname={pathname} role={membership?.role} onNavigate={() => setOpen(false)} /></div><Account email={email} membership={membership} /></>;
  return <div className="min-h-screen bg-[var(--paper)] font-sans md:flex"><aside className="hidden h-screen w-[17.5rem] shrink-0 flex-col bg-[var(--navy)] text-white md:sticky md:top-0 md:flex">{sidebar}</aside>{open && <div className="fixed inset-0 z-50 md:hidden"><button aria-label="Close navigation" className="absolute inset-0 bg-slate-950/70 backdrop-blur-sm" onClick={() => setOpen(false)} /><aside aria-label="Mobile workspace navigation" aria-modal="true" className="absolute inset-y-0 left-0 flex w-[min(88vw,22rem)] flex-col bg-[var(--navy)] text-white shadow-2xl" role="dialog"><button aria-label="Close navigation" className="focus-ring absolute right-3 top-3 z-10 rounded-md p-2 text-xl text-slate-300" onClick={() => setOpen(false)}>×</button>{sidebar}</aside></div>}<main className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-[4.5rem] items-center justify-between border-b border-[var(--line)] bg-white/95 px-4 backdrop-blur sm:px-6 lg:px-10"><div className="flex min-w-0 items-center gap-3"><button aria-expanded={open} aria-label="Open navigation" className="focus-ring flex h-10 w-10 items-center justify-center rounded-lg border border-[var(--line)] text-lg md:hidden" onClick={() => setOpen(true)}>☰</button><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--teal)]">{membership?.role === "viewer" ? "Read-only security workspace" : "Security operations"}</p><h1 className="truncate text-base font-semibold text-[var(--navy)] sm:text-lg">{current}</h1></div></div><div className="hidden items-center gap-3 sm:flex"><span className="h-2 w-2 rounded-full bg-emerald-500" aria-hidden="true"/><div className="text-right"><p className="max-w-52 truncate text-xs font-semibold text-[var(--navy)]">{membership?.organisationName}</p><p className="text-[10px] text-[var(--muted)]">Tenant-scoped workspace</p></div></div></header><div className="mx-auto w-full max-w-[96rem] p-4 sm:p-6 lg:p-10">{membership ? children : <section className="panel p-6"><h2 className="text-2xl font-semibold">Set up your company workspace</h2><p className="mt-3 text-sm text-[var(--muted)]">Create a company or join one with an invite. No company data is shown before access is confirmed.</p><Link className="button-primary mt-5 inline-block" href="/onboarding">Start setup</Link></section>}</div></main>{membership && pathname !== "/ai-analyst" && <Link aria-label="Open NHI Shield AI" className="focus-ring fixed bottom-4 right-4 z-40 flex items-center gap-2 rounded-full bg-[var(--teal)] px-4 py-3 text-sm font-semibold text-white shadow-xl sm:bottom-6 sm:right-6" href="/ai-analyst"><span className="rounded bg-white/15 px-1.5 py-0.5 text-[10px]">AI</span> Ask NHI Shield</Link>}</div>;
}
