import Link from "next/link";
import { BrandMark } from "@/components/brand-mark";

const links = [{ href: "/", label: "Home" }, { href: "/platform", label: "Platform" }, { href: "/security", label: "Security" }, { href: "/about", label: "About" }, { href: "/contact", label: "Contact" }];

export function PublicHeader() { return <header className="border-b border-[var(--line)] bg-white/95"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10"><Link href="/" className="focus-ring"><BrandMark /></Link><nav className="hidden items-center gap-7 md:flex" aria-label="Public navigation">{links.map((link) => <Link className="focus-ring text-sm text-[var(--muted)] transition-colors hover:text-[var(--ink)]" href={link.href} key={link.href}>{link.label}</Link>)}<Link className="focus-ring border border-[var(--navy)] px-4 py-2 text-sm font-semibold text-[var(--navy)]" href="/sign-in">Sign In</Link><Link className="focus-ring bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-white" href="/contact">Request a Pilot</Link></nav><Link className="focus-ring text-sm font-semibold text-[var(--navy)] md:hidden" href="/sign-in">Sign In</Link></div></header>; }

export function PublicFooter() { return <footer className="border-t border-[#29455b] bg-[var(--navy)] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-12 lg:grid-cols-[1.2fr_1fr] lg:px-10"><div><BrandMark light /><p className="mt-5 max-w-xs text-sm leading-6 text-slate-300">Machine Identity Security. Currently under development.</p></div><nav className="grid grid-cols-2 gap-x-8 gap-y-3 text-sm text-slate-300 sm:grid-cols-3" aria-label="Footer navigation">{links.slice(1).map((link) => <Link className="focus-ring hover:text-[var(--cyan)]" href={link.href} key={link.href}>{link.label}</Link>)}<Link className="focus-ring hover:text-[var(--cyan)]" href="/privacy">Privacy</Link><Link className="focus-ring hover:text-[var(--cyan)]" href="/terms">Terms of Use</Link></nav></div><div className="mx-auto flex max-w-7xl flex-col gap-2 border-t border-[#29455b] px-6 py-6 text-xs text-slate-400 lg:flex-row lg:justify-between lg:px-10"><span>© 2026 NHI Shield. All rights reserved.</span><span>Founded and developed by Phologa Mojapelo.</span></div></footer>; }

export function PublicLayout({ children }: Readonly<{ children: React.ReactNode }>) { return <div className="min-h-screen bg-[var(--paper)]"><PublicHeader /><main>{children}</main><PublicFooter /></div>; }