"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {requireSecurityContext,type SecurityContext} from "@/lib/security/context";
import {detectionKey,incidentRuleFor,type DetectionEvent} from "@/lib/security/incident-rules";
export type IncidentActionResult={ok:boolean;message?:string;error?:string};
const fail=(message="The activity request could not be completed."):IncidentActionResult=>({ok:false,error:message});
const activitySchema=z.object({machineIdentityId:z.string().uuid(),resourceId:z.string().uuid().optional(),action:z.string().trim().min(1).max(200),outcome:z.enum(["allowed","denied","error"]),occurredAt:z.string().datetime(),requestId:z.string().trim().max(200).optional()});
export async function submitActivity(_previous:IncidentActionResult,formData:FormData):Promise<IncidentActionResult>{
 try{const context=await requireSecurityContext("manage_security_inventory");const parsed=activitySchema.parse({machineIdentityId:formData.get("machineIdentityId"),resourceId:formData.get("resourceId")||undefined,action:formData.get("action"),outcome:formData.get("outcome"),occurredAt:new Date(String(formData.get("occurredAt"))).toISOString(),requestId:formData.get("requestId")||undefined});
 if(new Date(parsed.occurredAt).getTime()>Date.now()+300000)return fail("The activity time cannot be in the future.");
 const {data:identity}=await context.supabase.from("machine_identities").select("id").eq("organisation_id",context.organisationId).eq("id",parsed.machineIdentityId).maybeSingle();if(!identity)return fail("Choose an app or system account from this company.");
 if(parsed.resourceId){const {data:resource}=await context.supabase.from("resources").select("id").eq("organisation_id",context.organisationId).eq("id",parsed.resourceId).maybeSingle();if(!resource)return fail("Choose a resource from this company.");}
 const {error}=await context.supabase.from("activity_events").insert({organisation_id:context.organisationId,machine_identity_id:parsed.machineIdentityId,resource_id:parsed.resourceId??null,action:parsed.action,outcome:parsed.outcome,source:"manual",occurred_at:parsed.occurredAt,request_id:parsed.requestId??null,metadata:{}});if(error)return fail(parsed.requestId?"This activity request was already recorded.":undefined);revalidatePath("/incidents");revalidatePath("/overview");return{ok:true,message:"Activity recorded. Run incident analysis to check it."};}catch{return fail();}}
export async function runIncidentDetection(provided?:SecurityContext){
 const context=provided??await requireSecurityContext("investigate_incident");const since=new Date(Date.now()-86400000).toISOString();
 const [{data:events,error:eventError},{data:relationships,error:relationshipError},{data:activeIncidents,error:incidentError},{data:linkedEvents,error:timelineReadError}]=await Promise.all([context.supabase.from("activity_events").select("*,machine_identities(privilege_level),resources(sensitivity)").eq("organisation_id",context.organisationId).gte("occurred_at",since).order("occurred_at",{ascending:true}).limit(500),context.supabase.from("access_relationships").select("machine_identity_id,resource_id,privileged").eq("organisation_id",context.organisationId),context.supabase.from("incidents").select("id,detection_key,last_activity_at").eq("organisation_id",context.organisationId).neq("status","resolved").not("detection_key","is",null),context.supabase.from("incident_events").select("activity_event_id").eq("organisation_id",context.organisationId).not("activity_event_id","is",null)]);if(eventError||relationshipError||incidentError||timelineReadError)throw new Error("DETECTION_READ_FAILED");let created=0;let timelineEvents=0;
 const incidentByKey=new Map((activeIncidents??[]).filter(item=>item.detection_key).map(item=>[item.detection_key as string,{id:item.id,lastActivityAt:item.last_activity_at}]));const linked=new Set((linkedEvents??[]).map(item=>item.activity_event_id).filter(Boolean));
 for(const raw of events??[]){const event=raw as unknown as DetectionEvent;if(linked.has(event.id))continue;const relationship=event.resource_id?relationships?.find(item=>item.machine_identity_id===event.machine_identity_id&&item.resource_id===event.resource_id):undefined;const rule=incidentRuleFor(event,(events??[]) as unknown as DetectionEvent[],Boolean(relationship),Boolean(relationship?.privileged));if(!rule)continue;const key=detectionKey(rule.key,event);let active=incidentByKey.get(key);
  if(!active){const {data:incident,error}=await context.supabase.from("incidents").insert({organisation_id:context.organisationId,title:rule.title,description:`Deterministic rule ${rule.key} matched recorded activity.`,severity:rule.severity,machine_identity_id:event.machine_identity_id,resource_id:event.resource_id,opened_at:event.occurred_at,last_activity_at:event.occurred_at,detection_key:key}).select("id,last_activity_at").single();if(error||!incident)continue;active={id:incident.id,lastActivityAt:incident.last_activity_at};incidentByKey.set(key,active);created++;}
  else if(new Date(event.occurred_at)>new Date(active.lastActivityAt)){await context.supabase.from("incidents").update({last_activity_at:event.occurred_at}).eq("organisation_id",context.organisationId).eq("id",active.id);active.lastActivityAt=event.occurred_at;}
  const {error:timelineError}=await context.supabase.from("incident_events").insert({organisation_id:context.organisationId,incident_id:active.id,activity_event_id:event.id,event_type:"detection_rule",note:`Matched ${rule.key}.`,metadata:{rule:rule.key,denied_count:rule.deniedCount,window_minutes:15}});if(!timelineError){linked.add(event.id);timelineEvents++;}}
 await context.supabase.from("audit_events").insert({organisation_id:context.organisationId,actor_user_id:context.userId==="00000000-0000-0000-0000-000000000000"?null:context.userId,action:"incident_detection_run",entity_type:"organisation",entity_id:context.organisationId,metadata:{incidents_created:created,timeline_events_linked:timelineEvents,window_hours:24}});return created;
}
export async function detectIncidents(previous:IncidentActionResult,formData:FormData):Promise<IncidentActionResult>{void previous;void formData;try{const created=await runIncidentDetection();revalidatePath("/incidents");revalidatePath("/overview");return{ok:true,message:`Analysis complete. ${created} new incident${created===1?"":"s"} created.`};}catch{return fail("Incident analysis could not complete. Try again.");}}
export async function updateIncidentStatus(_previous:IncidentActionResult,formData:FormData):Promise<IncidentActionResult>{try{const context=await requireSecurityContext("investigate_incident");const id=z.string().uuid().parse(formData.get("id"));const status=z.enum(["open","investigating","contained","resolved"]).parse(formData.get("status"));const {data:current}=await context.supabase.from("incidents").select("status").eq("organisation_id",context.organisationId).eq("id",id).maybeSingle();if(!current)return fail("That incident was not found in this company.");const {error}=await context.supabase.from("incidents").update({status,resolved_at:status==="resolved"?new Date().toISOString():null}).eq("organisation_id",context.organisationId).eq("id",id);if(error)return fail();await context.supabase.from("incident_events").insert({organisation_id:context.organisationId,incident_id:id,event_type:"status_changed",note:`Status changed from ${current.status} to ${status}.`,metadata:{from:current.status,to:status}});revalidatePath(`/incidents/${id}`);revalidatePath("/incidents");return{ok:true,message:"Incident status updated."};}catch{return fail();}}
