"use server";
import { revalidatePath } from "next/cache";
import { requireSecurityContext } from "@/lib/security/context";
import { z } from "zod";
export type RemediationResult = { ok: boolean; message?: string; error?: string };
const proposalSchema = z.object({ title: z.string().trim().min(3).max(200), rationale: z.string().trim().min(5).max(2000), actionType: z.string().trim().min(2).max(100) });
const transitionSchema = z.object({ id: z.string().uuid(), target: z.enum(["approved","manual_action_required","succeeded","failed","cancelled"]), note: z.string().trim().max(1000).optional() });
export async function proposeRemediation(_previous: RemediationResult, formData: FormData): Promise<RemediationResult> { try { const context = await requireSecurityContext("propose_remediation"); const parsed = proposalSchema.parse({ title: formData.get("title"), rationale: formData.get("rationale"), actionType: formData.get("actionType") }); const { error } = await context.supabase.from("remediation_actions").insert({ organisation_id: context.organisationId, title: parsed.title, rationale: parsed.rationale, action_type: parsed.actionType, execution_mode: "manual", proposed_by: context.userId, status: "proposed" }); if (error) throw error; await context.supabase.from("audit_events").insert({ organisation_id: context.organisationId, actor_user_id: context.userId, action: "remediation_proposed", entity_type: "remediation", metadata: { action_type: parsed.actionType } }); revalidatePath("/remediation"); return { ok: true, message: "Proposal recorded for human review." }; } catch { return { ok: false, error: "The proposal could not be recorded." }; } }
export async function transitionRemediation(formData: FormData): Promise<void> { const context = await requireSecurityContext("approve_remediation"); const parsed = transitionSchema.parse({ id: formData.get("id"), target: formData.get("target"), note: formData.get("note") || undefined }); const {error}=await context.supabase.rpc("transition_remediation",{action_id:parsed.id,target_status:parsed.target,note:parsed.note??null}); if(error)throw new Error("REMEDIATION_TRANSITION_REJECTED"); revalidatePath("/remediation"); }
