export type RiskIdentity = { id: string; name: string; owner_name: string | null; privilege_level: string; last_seen_at: string | null };
export type RiskCredential = { id: string; label: string; status: string; expires_at: string | null; machine_identity_id: string };
export type RiskResource = { id: string; name: string; sensitivity: string };
export type RiskRelationship = { id: string; machine_identity_id: string; resource_id: string; privileged: boolean; machine_identities?: { name: string } | null; resources?: RiskResource | null };
export type RiskFinding = { findingType: string; title: string; description: string; severity: "low" | "medium" | "high" | "critical"; riskScore: number; confidence: number; machineIdentityId: string | null; resourceId: string | null; evidenceType: string; evidenceSummary: string; structuredData: Record<string, string | number | boolean | null>; source: string };

const STALE_DAYS = 90; const EXPIRY_WARNING_DAYS = 30;
export function evaluateIdentityRisk(identity: RiskIdentity, credentials: RiskCredential[], relationships: RiskRelationship[], resources: RiskResource[], now = new Date()): RiskFinding[] {
  const findings: RiskFinding[] = [];
  if (!identity.owner_name) findings.push({ findingType: "missing_owner", title: "Machine identity has no owner", description: `${identity.name} has no recorded owner. Ownership is needed for accountability and review.`, severity: "medium", riskScore: 35, confidence: 95, machineIdentityId: identity.id, resourceId: null, evidenceType: "identity_attribute", evidenceSummary: "No owner name is recorded for this machine identity.", structuredData: { owner_name_present: false }, source: "rule:missing_owner" });
  if (identity.privilege_level === "high" || identity.privilege_level === "critical") findings.push({ findingType: "high_privilege_identity", title: "Machine identity has elevated privilege", description: `${identity.name} is recorded with ${identity.privilege_level} privilege and should be reviewed against least-privilege expectations.`, severity: identity.privilege_level === "critical" ? "critical" : "high", riskScore: identity.privilege_level === "critical" ? 85 : 65, confidence: 95, machineIdentityId: identity.id, resourceId: null, evidenceType: "identity_attribute", evidenceSummary: `Recorded privilege level is ${identity.privilege_level}.`, structuredData: { privilege_level: identity.privilege_level }, source: "rule:high_privilege_identity" });
  if (identity.last_seen_at && new Date(identity.last_seen_at) < new Date(now.getTime() - STALE_DAYS * 86400000)) findings.push({ findingType: "stale_identity", title: "Machine identity has not been seen recently", description: `${identity.name} has a last-seen timestamp older than ${STALE_DAYS} days.`, severity: "medium", riskScore: 55, confidence: 90, machineIdentityId: identity.id, resourceId: null, evidenceType: "observed_timestamp", evidenceSummary: `Last observed at ${identity.last_seen_at}.`, structuredData: { stale_days: STALE_DAYS, last_seen_at: identity.last_seen_at }, source: "rule:stale_identity" });
  for (const credential of credentials) {
    if (credential.status === "expired" || (credential.expires_at && new Date(credential.expires_at) < now)) findings.push({ findingType: "expired_credential", title: "Credential metadata indicates expiry", description: `${credential.label} is expired or recorded as expired.`, severity: "critical", riskScore: 90, confidence: 100, machineIdentityId: identity.id, resourceId: null, evidenceType: "credential_metadata", evidenceSummary: `Credential ${credential.label} has an expiry condition.`, structuredData: { credential_id: credential.id, expires_at: credential.expires_at, status: credential.status }, source: "rule:expired_credential" });
    else if (credential.expires_at && new Date(credential.expires_at) <= new Date(now.getTime() + EXPIRY_WARNING_DAYS * 86400000)) findings.push({ findingType: "credential_expiring", title: "Credential metadata indicates approaching expiry", description: `${credential.label} is due to expire within ${EXPIRY_WARNING_DAYS} days.`, severity: "high", riskScore: 70, confidence: 100, machineIdentityId: identity.id, resourceId: null, evidenceType: "credential_metadata", evidenceSummary: `Credential ${credential.label} expires at ${credential.expires_at}.`, structuredData: { credential_id: credential.id, expires_at: credential.expires_at, warning_days: EXPIRY_WARNING_DAYS }, source: "rule:credential_expiring" });
  }
  for (const relationship of relationships) { const resource = relationship.resources ?? resources.find((item) => item.id === relationship.resource_id); if (relationship.privileged && resource && (resource.sensitivity === "high" || resource.sensitivity === "critical")) findings.push({ findingType: "privileged_sensitive_access", title: "Privileged access reaches a sensitive resource", description: `${identity.name} has privileged access to ${resource.name}.`, severity: "critical", riskScore: 85, confidence: 95, machineIdentityId: identity.id, resourceId: resource.id, evidenceType: "access_relationship", evidenceSummary: `Privileged relationship reaches a ${resource.sensitivity}-sensitivity resource.`, structuredData: { access_relationship_id: relationship.id, resource_sensitivity: resource.sensitivity, privileged: true }, source: "rule:privileged_sensitive_access" }); }
  return findings;
}

export const riskThresholds = { staleIdentityDays: STALE_DAYS, credentialExpiryWarningDays: EXPIRY_WARNING_DAYS, scoreRange: "0-100", confidenceMeaning: "Confidence measures the quality and directness of evidence supporting a deterministic rule, not probability of compromise." };