"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { BrandMark } from "@/components/brand-mark";
import { createClient } from "@/lib/supabase/browser";
import { signUpSchema } from "@/lib/validation/auth";

export default function SignUpPage() { const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); setMessage(null); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const result = signUpSchema.safeParse(values); if (!result.success) { setError(result.error.issues[0]?.message ?? "Check the form details."); return; } setBusy(true); const { error: authError } = await createClient().auth.signUp({ email: result.data.email, password: result.data.password, options: { data: { full_name: result.data.fullName, organisation_name: result.data.organisationName } } }); if (authError) { setError("Account creation could not be completed. Check the details or contact an administrator."); setBusy(false); return; } setMessage("Account created. Check your email if confirmation is enabled, then ask an organisation administrator to provision workspace access."); setBusy(false); }
  return <main className="sans min-h-screen bg-[var(--navy)] p-6 text-white"><div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-5xl items-center justify-center"><section className="grid w-full overflow-hidden rounded-sm bg-white text-[var(--ink)] shadow-2xl md:grid-cols-[0.85fr_1.15fr]"><div className="bg-[#173c59] p-10 text-white md:p-14"><BrandMark light /><h1 className="mt-20 font-serif text-5xl leading-[0.95]">A trusted starting point for your workspace.</h1><p className="mt-6 max-w-sm text-sm leading-6 text-slate-300">Create an authenticated account. Organisation access is provisioned separately and no privileged role is granted automatically.</p></div><div className="p-10 md:p-14"><Link className="focus-ring text-sm text-[var(--teal)]" href="/">← Return to website</Link><p className="mt-10 text-sm font-semibold uppercase tracking-wider text-[var(--teal)]">Create account</p><h2 className="mt-3 font-serif text-3xl">Start with your details</h2><form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-medium">Full name<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="fullName" type="text" required autoComplete="name" /></label><label className="block text-sm font-medium">Work email<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="email" type="email" required autoComplete="email" /></label><label className="block text-sm font-medium">Organisation name<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="organisationName" type="text" required autoComplete="organization" /></label><label className="block text-sm font-medium">Password<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="password" type="password" required minLength={8} autoComplete="new-password" /></label><label className="block text-sm font-medium">Confirm password<input className="focus-ring mt-2 w-full border border-[var(--line)] px-3 py-3" name="confirmPassword" type="password" required minLength={8} autoComplete="new-password" /></label>{error && <p className="text-sm text-red-700" role="alert">{error}</p>}{message && <p className="border-l-2 border-[var(--teal)] bg-[var(--teal-soft)] p-4 text-sm leading-6" role="status">{message}</p>}<button className="focus-ring w-full bg-[var(--teal)] px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={busy}>{busy ? "Creating account..." : "Create account"}</button></form><p className="mt-6 text-sm text-[var(--muted)]">Already have an account? <Link className="focus-ring font-semibold text-[var(--teal)]" href="/sign-in">Sign in</Link></p></div></section></div></main>; }