import Link from "next/link";
import { requireSecurityContext } from "@/lib/security/context";

type ImportRun = { id: string; entity_type: string; row_count: number; created_count: number; updated_count: number; status: string; analysis_status: string; created_at: string };

export default async function DataSourcesPage() {
  const context = await requireSecurityContext("view_security_data");
  const [{ data: imports }, { data: connectors }] = await Promise.all([
    context.supabase.from("import_runs").select("id, entity_type, row_count, created_count, updated_count, status, analysis_status, created_at").eq("organisation_id", context.organisationId).order("created_at", { ascending: false }).limit(25),
    context.supabase.from("connector_configurations").select("id, provider, status, last_sync_at").eq("organisation_id", context.organisationId).order("created_at", { ascending: false }),
  ]);
  const runs = (imports ?? []) as ImportRun[];
  return <section><p className="text-sm font-semibold uppercase tracking-wider text-[var(--teal)]">How data reaches NHI Shield</p><h2 className="mt-3 font-serif text-4xl">Data sources</h2><p className="mt-4 max-w-3xl text-sm leading-6 text-[var(--muted)]">CSV import is working now. Cloud connectors remain honestly Not Configured until credentials, least-privilege scopes, and a verified sync worker exist.</p><div className="mt-8 grid gap-4 md:grid-cols-2"><div className="border border-[var(--line)] bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Working</p><h3 className="mt-3 font-serif text-xl">CSV upload</h3><p className="mt-3 text-sm text-[var(--muted)]">Previewed, validated, transactional, tenant-scoped imports with duplicate handling and audit history.</p><Link className="focus-ring mt-5 inline-block bg-[var(--teal)] px-4 py-2 text-sm font-semibold text-white" href="/import">Add company data</Link></div>{["Microsoft Entra ID","Amazon Web Services","Google Cloud"].map((name) => <div className="border border-[var(--line)] bg-white p-6" key={name}><p className="text-xs font-bold uppercase tracking-wider text-amber-700">Not Configured</p><h3 className="mt-3 font-serif text-xl">{name}</h3><p className="mt-3 text-sm text-[var(--muted)]">Provider credentials, least-privilege scopes, and a secure scheduled worker are required. No discovery or sync is being simulated.</p></div>)}</div><div className="mt-10"><h3 className="font-serif text-2xl">Import history</h3><p className="mt-2 text-sm text-[var(--muted)]">Each confirmed file records its persistence and analysis-readiness status.</p>{!runs.length ? <div className="mt-4 border border-[var(--line)] bg-white p-6 text-sm text-[var(--muted)]">No confirmed imports yet. Download the realistic demo CSV to start.</div> : <div className="mt-4 overflow-x-auto border border-[var(--line)] bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#eef4f7] text-xs uppercase tracking-wider text-[var(--muted)]"><tr><th className="p-4">When</th><th className="p-4">Import</th><th className="p-4">Rows</th><th className="p-4">Persistence</th><th className="p-4">Analysis</th></tr></thead><tbody>{runs.map((run) => <tr className="border-t border-[var(--line)]" key={run.id}><td className="p-4">{new Date(run.created_at).toLocaleString()}</td><td className="p-4">{run.entity_type.replaceAll("_", " ")}</td><td className="p-4">{run.row_count}</td><td className="p-4 capitalize">{run.status}</td><td className="p-4 capitalize">{run.analysis_status}</td></tr>)}</tbody></table></div>}</div>{Boolean(connectors?.length) && <p className="mt-8 text-sm text-[var(--muted)]">{connectors?.length} connector configuration record{connectors?.length === 1 ? "" : "s"} belong to this organisation; their displayed status remains authoritative.</p>}</section>;
}
