import { removeMember, revokeInvite, updateMemberRole } from "@/lib/security/onboarding-actions";
import { InviteForm } from "@/components/invite-form";
import { requireSecurityContext } from "@/lib/security/context";
import { hasPermission, roleLabel } from "@/lib/security/permissions";

type Member = { user_id: string; role: "viewer" | "security_analyst" | "organisation_admin" | "platform_admin"; created_at: string };
type Invite = { id: string; role: Member["role"]; expires_at: string; max_uses: number; use_count: number; revoked_at: string | null; invited_email: string | null };

export default async function SettingsPage() {
  const context = await requireSecurityContext("view_security_data");
  const canManage = hasPermission(context.role, "manage_organisation");
  const [{ data: rawMembers }, { data: rawInvites }, { data: sources }] = await Promise.all([
    context.supabase.from("memberships").select("user_id, role, created_at").eq("organisation_id", context.organisationId).order("created_at"),
    context.supabase.from("organisation_invites").select("id, role, expires_at, max_uses, use_count, revoked_at, invited_email").eq("organisation_id", context.organisationId).order("created_at", { ascending: false }),
    context.supabase.from("ingestion_sources").select("id, name, status").eq("organisation_id", context.organisationId),
  ]);
  const members = (rawMembers ?? []) as Member[];
  const invites = (rawInvites ?? []) as Invite[];
  return <section>
    <p className="font-sans text-sm font-semibold uppercase tracking-wider text-[var(--teal)]">Organisation settings</p>
    <h2 className="mt-3 font-serif text-4xl">{context.organisationName}</h2>
    <p className="font-sans mt-4 text-sm leading-6 text-[var(--muted)]">Members, invites and ingestion sources for the current organisation.</p>
    <div className="mt-10"><h3 className="font-serif text-2xl">Members</h3>{!members.length ? <p className="font-sans mt-4 text-sm text-[var(--muted)]">No members found.</p> : <div className="mt-4 overflow-x-auto border border-[var(--line)] bg-white"><table className="w-full min-w-[680px] text-left font-sans text-sm"><thead className="border-b border-[var(--line)] bg-[#eef4f7] text-xs uppercase tracking-wider text-[var(--muted)]"><tr><th className="px-5 py-4">User</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Joined</th><th className="px-5 py-4">Actions</th></tr></thead><tbody>{members.map((member) => <tr className="border-b border-[var(--line)] last:border-0" key={member.user_id}><td className="px-5 py-4 font-mono text-xs">{member.user_id}</td><td className="px-5 py-4">{roleLabel(member.role)}</td><td className="px-5 py-4 text-[var(--muted)]">{new Date(member.created_at).toLocaleDateString()}</td><td className="px-5 py-4">{canManage && <div className="flex gap-2"><form action={updateMemberRole}><input type="hidden" name="userId" value={member.user_id} /><select className="border border-[var(--line)] px-2 py-1" name="role" defaultValue={member.role}><option value="viewer">Viewer</option><option value="security_analyst">Security Analyst</option><option value="organisation_admin">Organisation Admin</option></select><button className="ml-2 text-[var(--teal)]">Save</button></form><form action={removeMember}><input type="hidden" name="userId" value={member.user_id} /><button className="text-red-700">Remove</button></form></div>}</td></tr>)}</tbody></table></div>}</div>
    {canManage && <div className="mt-10 grid gap-8 lg:grid-cols-2"><section className="border border-[var(--line)] bg-[#eef4f7] p-6"><h3 className="font-serif text-2xl">Invite a member</h3><p className="font-sans mt-3 text-sm leading-6 text-[var(--muted)]">The plaintext code and secure link are returned once. Only the hash is stored. Email is sent through Supabase Auth when configured.</p><InviteForm /></section><section className="border border-[var(--line)] bg-white p-6"><h3 className="font-serif text-2xl">Invites</h3>{!invites.length ? <p className="font-sans mt-4 text-sm text-[var(--muted)]">No invites created.</p> : <div className="mt-4 space-y-3">{invites.map((invite) => { const expired = new Date(invite.expires_at) < new Date(); const used = invite.use_count >= invite.max_uses; const status = invite.revoked_at ? "Revoked" : expired ? "Expired" : used ? "Used" : "Pending"; return <div className="border-b border-[var(--line)] pb-3 font-sans text-sm" key={invite.id}><div className="flex justify-between gap-4"><span>{roleLabel(invite.role)}</span><span>{status}</span></div><p className="mt-1 text-xs text-[var(--muted)]">{invite.invited_email ?? "Any email"} · expires {new Date(invite.expires_at).toLocaleDateString()} · {invite.use_count}/{invite.max_uses} used</p>{status === "Pending" && <form action={revokeInvite} className="mt-2"><input type="hidden" name="inviteId" value={invite.id} /><button className="text-xs text-red-700">Revoke invite</button></form>}</div>; })}</div>}</section></div>}
    <section className="mt-10 border border-[var(--line)] bg-white p-6"><h3 className="font-serif text-2xl">Data Sources</h3><p className="font-sans mt-3 text-sm leading-6 text-[var(--muted)]">Manual Entry and CSV Import are available. External connectors are not configured.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Manual Entry · Available", "CSV Import · Available", "Azure / AWS / Google Cloud · Coming later"].map((source) => <div className="border border-[var(--line)] bg-[#eef4f7] p-4 font-sans text-sm" key={source}>{source}</div>)}</div>{sources?.map((source) => <p className="mt-4 font-sans text-sm" key={source.id}>{source.name} · {source.status}</p>)}</section>
  </section>;
}
